spring:

  application:
    name: JavaFinalProject8020

  # H2 database config
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  embedded-redis:
    port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    out-of-order: false
    clean-disabled: true

  quartz:
    job-store-type: memory
    auto-startup: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

springdoc:
  api-docs:
    path: /docs

logging:
  level:
    org.flywaydb.core.internal.sqlscript: DEBUG
    org.flywaydb: INFO
    org.quartz: INFO
    org.springframework.scheduling.quartz: DEBUG

app:
  properties:
    topic:
      sku-created: skuCreated
      replenishment: replenishment



